use hr;

SELECT oc.customer_id, customer_fname, customer_lname,
p.product_desc, SUM(oi.product_quantity) AS total_qty,
SUM(oi.product_quantity*p.product_price) AS total_amt
FROM online_customer oc 
JOIN order_header oh
    ON oc.customer_id=oh.customer_id
JOIN order_items oi
    ON oh.order_id=oi.order_id
JOIN product p
	ON oi.product_id=p.product_id
WHERE oc.customer_id=10
GROUP BY oc.customer_id, p.product_desc;


SELECT oc.customer_id, customer_fname, customer_lname,
p.product_desc, SUM(oi.product_quantity) AS total_qty,
SUM(oi.product_quantity*p.product_price) AS total_amt
FROM online_customer oc 
JOIN order_header oh
    ON oc.customer_id=oh.customer_id
JOIN Address a
	ON oc.address_id=a.address_id
JOIN order_items oi
    ON oh.order_id=oi.order_id
JOIN product p
	ON oi.product_id=p.product_id
WHERE a.state= 'Delhi'
GROUP BY oc.customer_id, p.product_desc;



SELECT IFNULL(oc.customer_id,'GRAND TOTAL>>') AS customer_id,
#CONCAT(customer_fname,' ', customer_lname) AS full_name,
IFNULL(p.product_desc, 'PROD LEVEL TOTAL>>') AS product_desc, 
IFNULL(pc.product_class_desc, 'CUST LEVEL TOTAL>>') AS product_class_desc, 
SUM(oi.product_quantity) AS total_qty,
SUM(oi.product_quantity*p.product_price) AS total_amt
FROM online_customer oc 
JOIN order_header oh
    ON oc.customer_id=oh.customer_id
    AND oh.order_status='Shipped'
JOIN Address a
	ON oc.address_id=a.address_id
JOIN order_items oi
    ON oh.order_id=oi.order_id
JOIN product p
	ON oi.product_id=p.product_id
JOIN product_class pc
	ON p.product_class_code=pc.product_class_code
WHERE a.state= 'Delhi'
GROUP BY oc.customer_id, pc.product_class_desc, p.product_desc WITH ROLLUP;


SELECT IFNULL(oc.customer_id,'GRAND TOTAL>>') AS customer_id,
#CONCAT(customer_fname,' ', customer_lname) AS full_name,
IFNULL(pc.product_class_desc,
		CONCAT('CUST id', oc.customer_id, 'Cust level total>>>')) AS product_class_desc,
IFNULL(p.product_desc, 
          CONCAT(product_class_desc, 'PROD LEVEL TOTAL>>')) AS product_desc, 
SUM(oi.product_quantity) AS total_qty,
SUM(oi.product_quantity*p.product_price) AS total_amt
FROM online_customer oc 
JOIN order_header oh
    ON oc.customer_id=oh.customer_id
    AND oh.order_status='Shipped'
JOIN Address a
	ON oc.address_id=a.address_id
JOIN order_items oi
    ON oh.order_id=oi.order_id
JOIN product p
	ON oi.product_id=p.product_id
JOIN product_class pc
	ON p.product_class_code=pc.product_class_code
WHERE a.state= 'Delhi'
GROUP BY oc.customer_id, pc.product_class_desc,p.product_desc WITH ROLLUP;


SELECT oc.customer_id, customer_fname, customer_lname, 
SUM(oi.product_quantity*p.product_price) AS total_amt
FROM online_customer oc
JOIN order_header oh 
     ON oc.customer_id=oh.customer_id
     AND oh.order_status='Shipped'
JOIN order_items oi
	ON oh.order_id=oi.order_id
JOIN product p
	ON oi.product_id=p.product_id
GROUP BY oc.customer_id

HAVING total_amt =(SELECT SUM(oi.product_quantity*p.product_price) AS total_amt
FROM online_customer oc
JOIN order_header oh 
     ON oc.customer_id=oh.customer_id
     AND oh.order_status='Shipped'
JOIN order_items oi
	ON oh.order_id=oi.order_id
JOIN product p
	ON oi.product_id=p.product_id
GROUP BY oc.customer_id
ORDER BY total_amt DESC LIMIT 1);




SELECT p.product_id, p.product_desc, 
SUM(oi.product_quantity) AS total_qty
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
    AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id
GROUP BY p.product_id
ORDER BY total_qty DESC;


SELECT p.product_id, p.product_desc, 
SUM(oi.product_quantity) AS total_qty
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
    AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id
WHERE p.product_price>1000
GROUP BY p.product_id
ORDER BY total_qty DESC;

SELECT p.product_id, p.product_desc, 
SUM(oi.product_quantity) AS total_qty
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
    AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id
GROUP BY p.product_id
HAVING total_qty=(SELECT SUM(oi.product_quantity) AS total_qty
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
    AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id
GROUP BY p.product_id
ORDER BY total_qty DESC LIMIT 1);

#total revenue generated by the most expensive product 

SELECT * FROM product;
SELECT * FROM order_items;
SELECT * FROM order_header;


SELECT p.product_id, p.product_desc,SUM(oi.product_quantity*p.product_price) AS total_amt
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
	AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id
GROUP BY p.product_id;

SELECT p.product_id, p.product_desc,p.product_price,SUM(oi.product_quantity*p.product_price) AS total_revenue
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
	AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id
WHERE p.product_price=(SELECT MAX(PRODUCT_PRICE) FROM product )
group by product_price;



# to find total rev of all products

SELECT p.product_id, p.product_desc,p.product_price,
SUM(oi.product_quantity*p.product_price) AS total_revenue,
  (
SELECT SUM(oi.product_quantity*p.product_price) 
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
	AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id  
  ) AS grand_total_rev, 
  (SELECT (total_revenue/SUM(oi.product_quantity*p.product_price))
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
	AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id  ) AS Ratio
FROM order_header oh 
JOIN order_items oi
	ON oh.order_id=oi.order_id
	AND oh.order_status='Shipped'
JOIN product p
	ON oi.product_id=p.product_id
WHERE p.product_price=(SELECT MAX(PRODUCT_PRICE) FROM product )
group by product_price;